name: build

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  build-x64:
    name: build for x64
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: pull repo
        uses: actions/checkout@v3
      - name: login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/vmops/lookbusy:latest-x64
  build-arm64:
    name: 构建arm64镜像
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - name: pull repo
        uses: actions/checkout@v3
      - name: login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/vmops/lookbusy:latest-arm64
  merge-image:
    name: merge image
    runs-on: ubuntu-24.04
    needs:
      - build-x64
      - build-arm64
    permissions:
        contents: read
        packages: write
    steps:
      - name: login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: merge image
        run: |
          docker manifest create ghcr.io/vmops/lookbusy:latest --amend ghcr.io/vmops/lookbusy:latest-x64 --amend ghcr.io/ghcr.io/vmops/lookbusy:latest-arm64
          docker manifest push ghcr.io/vmops/lookbusy:latest          